exp_name: ppo/test_new_III
num_episodes: 1.0e+6
log_every: 10
save_every: 100
gamma: 0.99
lam: 0.95
coef_value: 0.500
coef_entropy_max: 0.015
coef_entropy_min: 0.010
coef_entropy_elbow: 2.5e+4
max_grad_norm: 0.500
num_envs: 24
clip_eps: 0.20
clip_value_loss: true
minibatch_size: 512
num_epochs: 4

model:
  # Core encoder
  dim_entity: 64
  transformer_dim_ff: 128
  transformer_num_heads: 4
  transformer_num_blocks: 2
  map_encoder_kernel_size: 3
  map_encoder_dim: 64

  # Head dimensions
  dim_ff_primary: 64
  dim_ff_card: 64
  dim_ff_monster: 64
  dim_ff_map: 64
  dim_ff_value: 64

optimizer:
  name: Adam
  kwargs:
    lr: 1.0e-4
