exp_name: a2c/jaw/test-parallel-fix-II
num_episodes: 1.0e+6
log_every: 10
save_every: 100
gamma: 0.99
lam: 0.95
coef_value: 0.500
coef_entropy_max: 0.020
coef_entropy_min: 0.010
coef_entropy_elbow: 5.0e+4
max_grad_norm: 0.500
num_eval: 100
num_envs: 8
clip_eps: 0.20
clip_value_loss: true
minibatch_size: 64
num_epochs: 4

model: 
  embedding_dim_card: 64
  embedding_dim_char: 64
  embedding_dim_monster: 64
  embedding_dim_energy: 16
  num_heads: 8

optimizer:
  name: Adam
  kwargs:
    lr: 1.0e-4
